### ISSUE TITLE
How to use with Sigil?

### ISSUE THREAD

**Issue by ITfee** [Sigil-Ebook/flightcrew#47] opened 2016-01-13 11:43 UTC
When I choose "Manage Plugins" and add the Flightcrew-Plugin to Sigil there seems to be no change, i.e. I can't find neither an option nor an icon to validate a loaded epub-file. So how do I validate an epub with Flightcrew?

**Comment by AGSPhoenix** [comment] 2016-07-24 02:26
After installing the plugin, a new validate menu should appear in the plugins menu. You can also assign one of the plugin buttons to FlightCrew from the plugin settings page.

**Comment by chumblefish** [comment] 2016-07-28 06:22
To all those who haven't a clue how to use the plugin but somehow manage to find this page, you don't actually install the plugin. Just move the downloaded zip file to a safe place where it won't be deleted (I'm guessing that's a good idea), then in Sigil you can see a menu called "plugins". Click that, click "manage plugins" and then click "add plugin". Then find the zip file and choose that. Then at the bottom you can assign it (as plugin 1 for example) and then once you've opened your ebook file, click the plugin 1 icon or "plugins", "validation", "flight crew".

Not sure why instructions can't be placed on the download page. I'm not a computer genius and there's a lot of other non-computer geniuses out there who could be saved the heartache of trying to work out what to do with the downloaded file. Anyway, nevertheless, thanks for this free software.

**Comment by wrcstewart** [comment] 2017-02-03 17:31
Using OS X - carry out this procedure but the plugin remains greyed out so i cannot add it. Also tried clicking on it then allowing opening in security preferences. But the plug remains dry whatever I  do....
Anyone had this problem?

**Comment by JulesleMer** [comment] 2017-03-22 11:22
I had a similar problem, and as chumblefish says above the answer is on the Add Plugin Dialogue to choose the zip file (FlightCrew_v0.9.1osx.zip) not the unzipped plugin flightcrew-plugin

**Comment by dougmassay** [comment] 2017-03-22 11:32
Plugins should never be unzipped or renamed. Sigil's Plugin Manager only accepts .zip files. The name of a zip file needs to match the internal structure of the archive, so renaming it will render the plugin invalid as well.

In short: plugins ARE zip files. Dwnload plugin zip files ... Add plugin zip files with the Plugin Manager. Anything else (including browser download addons that rename files) will break a Sigil plugin.

Also make sure Safari isn't automatically unzipping zip archives after download.

**Comment by klgc** [comment] 2019-02-09 06:43
Gaaaaaaa####!  The comments above seem straight forward, but there's a catch. I upgraded (from 0.8.7) to Sigil 0.9.8 from GitHub and the notes say that now the epub2 validator FlightCrew is a plugin and the latest version (0.9.1) should also be downloaded and installed.

I'm on MacOS 10.13.6 so on GitHub I chose the download FlightCrew_v0.9.1osx.zip  The problem is that the plugin file in the osx folder is a Unix executable file, not a zip file, so of course it's grayed out when I try to add the plugin. 

Will someone please tell me how to get the horse hooked up to the buggy. Don't mean to seem so dense, but I'm a nearly 80yo author that's trying to complete a book. Thank you kind souls in advance :-)

**Comment by dougmassay** [comment] 2019-02-09 10:44
The very last  line of the comment just above yours contains the relevant info. Your browser (Safari) is being too "helpful" and automatically unzipping downloaded zip files for you. You need to tell it not to do that. A Sigil plugin is a zip file and must be installed as a zip file.

**Comment by chumblefish** [comment] 2019-02-09 10:49
There's some info at the link below on how to stop Safari from automatically unzipping zip files ...

[https://apple.stackexchange.com/questions/961/how-to-stop-safari-from-unzipping-files-after-download](url)

**Comment by chumblefish** [comment] 2019-02-09 10:52
Incidentally, is there any way to add this info about how to install the plugins on the plugin download page? I guess a lot of people get stumped by this and perhaps never stumble upon this thread. A few helpful lines would probably prevent a lot of head-scratching for the less technically minded.

**Comment by dougmassay** [comment] 2019-02-09 11:03
It's really only been a handful of Safari users that get tripped up, but we'll consider it. No other browser out there defaults to unzipping downloaded archives out of the box, and we're not really here to teach people how to correct what their browsers are getting wrong.

**Comment by chumblefish** [comment] 2019-02-09 15:33
Hi Doug, I was tripped up as a windows user. As far as I can see, there are no instructions on this page ...
[https://github.com/Sigil-Ebook/flightcrew/releases](url)

**Comment by klgc** [comment] 2019-02-09 17:00
Ah yes, good ol' Mac making things simple for us simple folks (irony). I unchecked "Open 'safe' files after downloading" in Safari preferences General tab, downloaded the new version of flightcrew plugin again, moved the zip file to Library Plugins folder for safekeeping, and added it to Sigil as per instructions above.

Back in business with the validation function now. Much obliged kind souls :-)

**Comment by dougmassay** [comment] 2019-02-09 17:01
> Back in business with the validation function now. Much obliged kind souls :-)

Glad to hear it!

**Comment by kevinhendricks** [comment] 2023-07-28 22:14
Closing as this repo is being archived.

**Closed by kevinhendricks** 2023-07-28 22:14 UTC
